name: Graph
on:
  # Schedule updates (each hour)
  schedule:
    - cron: '30 * * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch: ~
  push: {branches: ["master", "main"]}
jobs:
  Metrics:
  # https://github.com/lowlighter/metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jhihyulin
          template: classic
          base: header
          config_timezone: Asia/Taipei
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
