name: Graph
on:
  # Schedule updates (each hour)
  schedule:
    - cron: '30 * * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch: ~
  push: {branches: ["master", "main"]}
jobs:
  Metrics:
  # https://github.com/lowlighter/metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: jhihyulin
          template: classic
          base: header
          config_timezone: Asia/Taipei
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  Summary-card:
  # https://github.com/vn7n24fzkq/github-profile--cards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env: # default use ${{ secrets.SUMMARY_GITHUB_TOKEN }}, you should replace with your personal access token
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8 
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: ""
